# Generated by Django 2.2 on 2019-10-02 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 21, 44, 2, 178075)),
        ),
    ]
