# Generated by Django 2.2 on 2019-10-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191003_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_creator', models.CharField(max_length=100)),
                ('v_code', models.CharField(max_length=20)),
                ('v_amount', models.CharField(max_length=200)),
                ('ref_no', models.CharField(max_length=100)),
                ('v_status', models.CharField(max_length=10)),
                ('v_loader', models.CharField(max_length=100)),
                ('v_date_load', models.CharField(max_length=100)),
                ('v_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
