# Generated by Django 2.2 on 2019-10-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('priority', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('ticket_id', models.CharField(max_length=10)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_action', models.CharField(max_length=100)),
            ],
        ),
    ]
