# Generated by Django 2.2 on 2019-10-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_owner_username', models.CharField(max_length=100)),
                ('bus_name', models.CharField(max_length=200)),
                ('bus_address', models.CharField(max_length=200)),
                ('bus_email', models.CharField(max_length=100)),
                ('bus_no', models.CharField(max_length=20)),
                ('bus_website', models.CharField(max_length=200)),
                ('api_test_key', models.CharField(max_length=200)),
                ('api_live_key', models.CharField(max_length=200)),
            ],
        ),
    ]
