# Generated by Django 2.2 on 2019-10-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='ref_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
