# Generated by Django 2.2 on 2019-10-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_withdraw_ref_no'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
        migrations.AlterModelTable(
            name='bank',
            table='bank',
        ),
        migrations.AlterModelTable(
            name='merchant',
            table='merchant',
        ),
        migrations.AlterModelTable(
            name='merchantpayment',
            table='merchantPayment',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
        migrations.AlterModelTable(
            name='transactions',
            table='transactions',
        ),
        migrations.AlterModelTable(
            name='voucher',
            table='voucher',
        ),
        migrations.AlterModelTable(
            name='withdraw',
            table='withdraw',
        ),
    ]
