# Generated by Django 2.2 on 2019-10-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20191012_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='bus_logo',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
