# Generated by Django 2.2 on 2019-10-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_invoice_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.AlterField(
            model_name='merchant',
            name='bus_logo',
            field=models.FileField(upload_to='media'),
        ),
    ]
