# Generated by Django 2.2 on 2019-10-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20191023_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=10)),
                ('date_paid', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
