# Generated by Django 2.2 on 2019-10-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
