# Generated by Django 2.2.7 on 2019-11-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_subscription_date_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='int_mode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='w_p_charges',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
