# Generated by Django 2.2.7 on 2019-12-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='amount',
            field=models.FloatField(),
        ),
    ]
