# Generated by Django 2.2 on 2019-10-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.CharField(max_length=1000)),
                ('contact_us', models.CharField(max_length=1000)),
                ('pricing', models.CharField(max_length=1000)),
            ],
        ),
    ]
