# Generated by Django 2.2 on 2019-10-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0002_settings'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resolution',
            table='resolution',
        ),
        migrations.AlterModelTable(
            name='settings',
            table='settings',
        ),
    ]
