# Generated by Django 2.2 on 2019-10-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0004_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='contact_us',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='pricing',
            new_name='phone_no',
        ),
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
