# Generated by Django 2.2.7 on 2019-11-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0006_settings_paystack_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=2000)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'emails',
            },
        ),
    ]
